/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 21 03:01:07 GMT 2018
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.Node;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Node_ESTest extends Node_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Node<String> node0 = new Node<String>("^r{Zo]");
      String string0 = node0.getObject();
      assertEquals("^r{Zo]", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer integer0 = new Integer((-822));
      Node<Object> node0 = new Node<Object>(integer0);
      node0.setNext(node0);
      Node<Object> node1 = node0.getNext();
      assertSame(node1, node0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Node<String> node0 = new Node<String>((String) null);
      node0.setNext((Node<String>) null);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Node<String> node0 = new Node<String>((String) null);
      String string0 = node0.getObject();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Node<String> node0 = new Node<String>((String) null);
      Node<String> node1 = node0.getNext();
      assertNull(node1);
  }
}
